package com.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrame {
    private JButton btnLissajouxPanel;
    private JButton btnRandomPanel;
    private JPanel pnlMain;
    private JPanel pnlMainFrame;

    private Scratch scratch = new Scratch();
    private LissajouxPanel lissajouxPanel = new LissajouxPanel();

    public MainFrame() {
        btnLissajouxPanel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                scratch.stopDraw();
                //pnlMain.remove(scratch);
                pnlMain.removeAll();
                pnlMain.setLayout(new BorderLayout());

                pnlMain.add(lissajouxPanel.panel, BorderLayout.CENTER);
                pnlMain.revalidate();
            }
        });
        btnRandomPanel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                pnlMain.removeAll();
                pnlMain.setLayout(new BorderLayout());
                pnlMain.add(scratch, BorderLayout.CENTER);
                scratch.startDraw();
                pnlMain.revalidate();
            }
        });
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("Some drawing stuffs");
        JPanel panel = new MainFrame().pnlMainFrame;
        frame.setContentPane(panel);
        //frame.setPreferredSize(new Dimension(640, 480));
        frame.setPreferredSize(panel.getPreferredSize());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }


    ///////////////////////////////////////////////////////////

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMainFrame = new JPanel();
        pnlMainFrame.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 10, 10, 10), -1, -1));
        pnlMainFrame.setMinimumSize(new Dimension(900, 500));
        pnlMainFrame.setOpaque(true);
        pnlMainFrame.setPreferredSize(new Dimension(1024, 768));
        btnLissajouxPanel = new JButton();
        btnLissajouxPanel.setMargin(new Insets(0, 0, 0, 0));
        btnLissajouxPanel.setText("Lissajoux");
        pnlMainFrame.add(btnLissajouxPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRandomPanel = new JButton();
        btnRandomPanel.setMargin(new Insets(0, 0, 0, 0));
        btnRandomPanel.setText("Random Panel");
        pnlMainFrame.add(btnRandomPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pnlMain = new JPanel();
        pnlMain.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pnlMainFrame.add(pnlMain, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        pnlMain.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMainFrame;
    }

}